---
web_package: apache2
web_service: apache2
web_docroot: /var/www/html
web_owner: www-data
web_group: www-data
web_server_name: lamp-demo.local
web_listen_port: 80
web_security_headers: []
web_extra_packages: []
web_extra_modules:
  - headers
