---
env_name: prod
app_debug: false
web_security_headers:
  - name: X-Content-Type-Options
    value: "nosniff"
  - name: X-Frame-Options
    value: "DENY"
  - name: X-XSS-Protection
    value: "1; mode=block"
  - name: Strict-Transport-Security
    value: "max-age=63072000; includeSubDomains; preload"
php_display_errors: "Off"
php_error_reporting: E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
database_bind_address: 127.0.0.1
assert_expected_port: 80
