---
php_packages:
  - php
  - libapache2-mod-php
  - php-mysql
php_conf_dir: /etc/php/8.3/apache2/conf.d
php_custom_ini: 99-demo.ini
php_apache_service: apache2
php_display_errors: On
php_error_reporting: E_ALL
php_timezone: Europe/Warsaw
